builds:
  - id: git
    main: ./cmd/git
    binary: plugins/modules/git
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - builds:
      - git
release:
